  # tic documentation: https://docs.ropensci.org/tic/dev/

# Download script file from GitHub
init:
  ps: |
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - cmd: Rscript -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
  - cmd: Rscript -e "getOption('repos')"
  - cmd: Rscript -e "if (!requireNamespace('remotes')) install.packages('remotes', type = 'binary')"
  - cmd: Rscript -e "if (getRversion() < '3.2' && !requireNamespace('curl')) install.packages('curl', type = 'binary')"
  - cmd: Rscript -e "options(pkgType = 'binary'); remotes::install_github('ropensci/tic', upgrade = 'always'); print(tic::dsl_load()); tic::prepare_all_stages()"

before_build: Rscript -e "tic::before_install()"
build_script: Rscript -e "tic::install()"
after_build: Rscript -e "tic::after_install()"
before_test: Rscript -e "tic::before_script()"
test_script: Rscript -e "tic::script()"
on_success: Rscript -e "try(tic::after_success(), silent = TRUE)"
on_failure: Rscript -e "tic::after_failure()"
before_deploy: Rscript -e "tic::before_deploy()"
deploy_script: Rscript -e "tic::deploy()"
after_deploy: Rscript -e "tic::after_deploy()"
on_finish: Rscript -e "tic::after_script()"

# no testing on R-devel because no package binaries are available
environment:
  matrix:
    - R_VERSION: release
    - R_VERSION: oldrel
  id_rsa:
    secure: g3Kfde3Cu+CYLXiu69imcR8K0oAqfut2IbHOmx7w9i9xRcfl2mZgrRLVLcotg4XbvL7xE8Vq4M1XH/n/s5bNOZINPkIA3ILL5vFuxzPvDGbHG+EN9TqRTnCmunblAXv8mTxu+hpLKUe6A2kUdNUj/mQQDTXrO49UkqhNVLP7fdHV5tE6ybW/LhrFJLaqYKla8ezjpPzLpNzrqTgc71Nyf2ccKmbHc/sKAvkLkboj4ja0AtzMs6IMbBaaKKZAgtdw8pKtLSaIIIOc48jiUPUYt8jMOkAjf1QJpT6h98z57oPrwVDCZhSfFHc0pGbkSeL7jdo93xLOBKSPClJDaAgZ5BB1rT+AcMnNBqswhi6shtnOpfpZuPWOQf7uEE8qDhC7ckilJkbdrwpM5mnY0r7XQA4Vyu1lD3QeyiUF6PpJPXAE9DcIr41+Aa9Z8azmYF9zKuxAmWcmxP+ABCW3TiY1o91nM5otiqBzvplxHDIrreUZmBgChwacvNl2AlMFfjZ+V5LSOru1+2wAZgKfd/TJHSyCtMa9eT0FqsgO/wi8MXDX5gzFGEnDOr03kuN7D6olugV3NXUhnc5/Ck01LHpiJy/5pAqS1joKMTtAikQLkST496pcIv/UmryR67pUVLags+hzLrqYs3ib6hMR5C/E8oeSfsmsaSQIjTpgjiKNZ2FtVrKYz4Gbdvozn67MJq3z6lG6dy84vAwZE4kcOnzmchEg39s97g5esjEWd6WUDDCHHpDtfUVT0m0alONVy9nA1ukErV14SjzeZTOb+YnOmkQz21BkiIWVP5QLENiYwUGaPfqmfzFaqm3GTDSoMX9SriQlOsFhOl5HPTCtdZmMSdeZ6SCDTHAfvL+SSADAXs9AmsiOCujZybl4HJvR4n0QZ6vCVxpX1Rk+0mP17oTuF86e6BrNYm0xQzylo/7rX8NuugGyJsQfTy9aiZzay0QEXhdabhIsJ90K4aHaWT6v33B7LohI5qDOVQDC5e1c+XljrIXd/Aq0kscR4bT6qlsfW6OnOD9y3ofXP7jZ5eJgUsS/vqjKAbwPvqzvJ/LJaXRO8c8LEuIOlu/RAh77l7Ic5dYUVIgGoI/4O3O/YmrkNNu/AjwDMjYys53PA5zw/LrSPA9nlaRszttIeoiphY5jeCBdf6f6c5IM2rNWCgECyzgF/V/p1ZogCu/blHeG5Qqds7DUeBrdrxJ893+M0Vpss2KgnduJlZRYsNgrX3jFStxmaK/y+BydaX3xEa6NnU1HOVXECSv/uoX1f8qH2tyUjM6y1qc3dSVd7k6WGBk/LFKFBFYqmT0cjlCB6pyZM0igjxdMdU/leGs82WCz8QOghvo5tA0h/8+vtCfm8RWEAD1OSc00HTFzSremf59R+V716/9uQ6sFJKCrNe9oCUxzoCre0e6yLasslz/KL/Lv+StChIj72dLBIiDCzpDr2J1OD7s9L9xWwlxFTeZCrvO0OR4YVD1RB0DsEMhU8vnT2uAfTVqRvzklGtElq/bOVgdJG9L0oR3fPd8CS6Nb/wbA+0uydJMrS9nyRUhai1Vdq4M0yNpO+avovPEEuPS1S4A45jYWuLpj3SoFdSaiqbKvEkTxaKZUku/0eBorO9v5yNuMM2AbWHXj8Mgm0kAvkEx1f+MFn6ymA6/g7pI42BfEri5tj20IzUaeLDoYKKEddxurPI0LxS+STL2sGqaYMp4PblXRhlHR39ge1X5OKAJ9/PvQloPHdejn+Lv9bhiJujYyOK5zpkxQZpBnOk87KQRu5PEs0udnaR9CmVBPTjfcRmJTV9MjZKuzOGI7t+Fj8+chQLaTPx61wOMH00lqrQO4ijH5nrBLNhr0NCH5U1oWpJCoZZEnx6kRycDzJltwBAKJYePB5s9mLD8xUlT1lrMQ1P1xrni9cyzJsuTI+hvOxNGOPwdh2ZLGW2IdMfL6MEhCLqi8qSxv9m8krtMQg7ih2ML0GJcMWGt8jJETmICxJ8bReZ1sHJM2AdMLYu5XPS4sbpvE17fo1/r0tIWwFseC2Px6/JFkxlg287g1mNVT8OCLu6eQqJu93mxHkHOhA6z/d3NBfE1iaeMHBvF8D9mftTQ1aX5m/rsVsWpfnYuNeNY3Q7tPbiPQK/X9So4JhAipamXOJsg+JVRvYHKG44Bokvk3F8CZaGEBGkvYQvG1vPeyztq+3OgG6ZDIEkSVqQkJWD8ky3Hl+cRQ4SI2ycgNtIRHKPYNk41WQBJy3x7KuGBmj12qEUkSSf+zrtJuIGD0nLVUPWkl/Z/z0eViMGCvj5LD9HSg+dHXjL3qPPfTeYE9G3yhElLHP16zRLw5HnNN9s0fAJkgpAVJsId0Nv75TELapDjmOcfCyqTZampj/rEzdzjncLDkv4CwpUG9N1Y/InUMZzx9u39p/sUXeAmB/F23gek7h75fvMx4c0B575epEiD2e5eIO5m31xosuu2MfgpfIaFbCxs/dgitSby9fIU3G9dPmkFeYujZ/1OOuguy5eQq0eiyEv8X92JHvuTl1cNzCAs2gP1HbDa3K921DW6+6nPKXJhUfoqnG4KdV6+eac3u5Vln/NkC5ZepODXvPEJoxo8gkB36KUEzysJ283izRn9Zgvy9NYNus8Ir5S3wUKoRTBCLzkUjoMzKN6UJ73AeHmcOUuP0hJIeL6myMdHexZI1SKRMq79vjvWO3UnHDrnkNdzfusQ+dLU636qO2BoVneY07avV6cwqWrsr3CDvtIDhzd7922Nu4iBarXSj6roerG1N2HRt3DDgp7EpjohnL6vWVg52CF3NNZxYAHSzWUidSfyGssoHvuJCF8wU5irW2RT9tYF8Jyawco20NTB54GP25XFhxfiveX1ZyfdQQJ08KGKJIDa5F2ue5yYoUACX8AqLtU5DsQ+qXmRp1deUsh+YG0rfl2xULxtBknBkSVaINtUYCod5eAfGovMsIdMSD0XERMtHaaEMTEtjhLdSXgG9hBJISkGaewsGcMnGBYtELYpiF9lDhflbxS/2BAEGMmwQBj6K3YvRlAs00myZIjchEnAIKmT74II=
  USE_RTOOLS: true

matrix:
  fast_finish: true
# Custom user code -------------------------------------------------------------
